apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sqlserver.fullname" . }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sqlserver.labels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "sqlserver.labels" . | nindent 8}}
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: {{ include "sqlserver.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.sqlserverVersion }}"
        imagePullPolicy: {{.Values.image.pullPolicy }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10}}
{{- end }}
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "sqlserver.fullname" . }}
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: {{ include "sqlserver.fullname" . }}-data
