apiVersion: v1
data:
  MSSQL_SA_PASSWORD: {{ randAlphaNum 12 |b64enc}}
kind: Secret
metadata:
  name: {{ include "sqlserver.fullname" . }}
  labels:
    {{- include "sqlserver.labels" . | nindent 4 }}
type: Opaque
