apiVersion: v1
kind: Service
metadata:
  name: {{ include "sqlserver.fullname" . }}-deployment
spec:
  selector:
    {{- include "sqlserver.labels" . | nindent 4 }}
  ports:
  - name: {{ include "sqlserver.fullname" . }}-port
    nodePort: {{ .Values.service.nodePort | default "30433" }}  
    protocol: TCP
    port: 1433
    targetPort: 1433
  type: {{ .Values.service.type }}
